language: android
sudo: false

env:
  - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

jdk:
  - oraclejdk8

android:
  components:
    - android-25
    - build-tools-25.0.3
    - extra-android-m2repository

  licenses:
    - android-sdk-license-.+

script:
  - ./gradlew build
