language: android
jdk:
  - oraclejdk8
env:
  - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

android:
  components:
    - tools
    - build-tools-25.0.3
    - android-25

  licenses:
    - android-sdk-license-.+

script:
  - ./gradlew clean build
